// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-rod/rod"
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/internal/repository"
)

// NewBrowserRepositoryMock creates a new instance of BrowserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserRepositoryMock {
	mock := &BrowserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowserRepositoryMock is an autogenerated mock type for the BrowserRepository type
type BrowserRepositoryMock struct {
	mock.Mock
}

type BrowserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowserRepositoryMock) EXPECT() *BrowserRepositoryMock_Expecter {
	return &BrowserRepositoryMock_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type BrowserRepositoryMock
func (_mock *BrowserRepositoryMock) Connect(ctx context.Context) (*rod.Browser, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *rod.Browser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*rod.Browser, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *rod.Browser); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rod.Browser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrowserRepositoryMock_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type BrowserRepositoryMock_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BrowserRepositoryMock_Expecter) Connect(ctx interface{}) *BrowserRepositoryMock_Connect_Call {
	return &BrowserRepositoryMock_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *BrowserRepositoryMock_Connect_Call) Run(run func(ctx context.Context)) *BrowserRepositoryMock_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrowserRepositoryMock_Connect_Call) Return(browser *rod.Browser, err error) *BrowserRepositoryMock_Connect_Call {
	_c.Call.Return(browser, err)
	return _c
}

func (_c *BrowserRepositoryMock_Connect_Call) RunAndReturn(run func(ctx context.Context) (*rod.Browser, error)) *BrowserRepositoryMock_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// NewPage provides a mock function for the type BrowserRepositoryMock
func (_mock *BrowserRepositoryMock) NewPage(ctx context.Context) (repository.Page, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewPage")
	}

	var r0 repository.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (repository.Page, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) repository.Page); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrowserRepositoryMock_NewPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPage'
type BrowserRepositoryMock_NewPage_Call struct {
	*mock.Call
}

// NewPage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BrowserRepositoryMock_Expecter) NewPage(ctx interface{}) *BrowserRepositoryMock_NewPage_Call {
	return &BrowserRepositoryMock_NewPage_Call{Call: _e.mock.On("NewPage", ctx)}
}

func (_c *BrowserRepositoryMock_NewPage_Call) Run(run func(ctx context.Context)) *BrowserRepositoryMock_NewPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrowserRepositoryMock_NewPage_Call) Return(page repository.Page, err error) *BrowserRepositoryMock_NewPage_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *BrowserRepositoryMock_NewPage_Call) RunAndReturn(run func(ctx context.Context) (repository.Page, error)) *BrowserRepositoryMock_NewPage_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type BrowserRepositoryMock
func (_mock *BrowserRepositoryMock) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BrowserRepositoryMock_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type BrowserRepositoryMock_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BrowserRepositoryMock_Expecter) Ping(ctx interface{}) *BrowserRepositoryMock_Ping_Call {
	return &BrowserRepositoryMock_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *BrowserRepositoryMock_Ping_Call) Run(run func(ctx context.Context)) *BrowserRepositoryMock_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrowserRepositoryMock_Ping_Call) Return(err error) *BrowserRepositoryMock_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrowserRepositoryMock_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *BrowserRepositoryMock_Ping_Call {
	_c.Call.Return(run)
	return _c
}
