// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/internal/repository"
)

// NewBrowserMock creates a new instance of BrowserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserMock {
	mock := &BrowserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowserMock is an autogenerated mock type for the Browser type
type BrowserMock struct {
	mock.Mock
}

type BrowserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowserMock) EXPECT() *BrowserMock_Expecter {
	return &BrowserMock_Expecter{mock: &_m.Mock}
}

// Chromium provides a mock function for the type BrowserMock
func (_mock *BrowserMock) Chromium() repository.BrowserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chromium")
	}

	var r0 repository.BrowserRepository
	if returnFunc, ok := ret.Get(0).(func() repository.BrowserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BrowserRepository)
		}
	}
	return r0
}

// BrowserMock_Chromium_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chromium'
type BrowserMock_Chromium_Call struct {
	*mock.Call
}

// Chromium is a helper method to define mock.On call
func (_e *BrowserMock_Expecter) Chromium() *BrowserMock_Chromium_Call {
	return &BrowserMock_Chromium_Call{Call: _e.mock.On("Chromium")}
}

func (_c *BrowserMock_Chromium_Call) Run(run func()) *BrowserMock_Chromium_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrowserMock_Chromium_Call) Return(browserRepository repository.BrowserRepository) *BrowserMock_Chromium_Call {
	_c.Call.Return(browserRepository)
	return _c
}

func (_c *BrowserMock_Chromium_Call) RunAndReturn(run func() repository.BrowserRepository) *BrowserMock_Chromium_Call {
	_c.Call.Return(run)
	return _c
}
