// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/internal/repository"
)

// NewElementMock creates a new instance of ElementMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElementMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElementMock {
	mock := &ElementMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ElementMock is an autogenerated mock type for the Element type
type ElementMock struct {
	mock.Mock
}

type ElementMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ElementMock) EXPECT() *ElementMock_Expecter {
	return &ElementMock_Expecter{mock: &_m.Mock}
}

// Attribute provides a mock function for the type ElementMock
func (_mock *ElementMock) Attribute(ctx context.Context, name string) (*string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Attribute")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElementMock_Attribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attribute'
type ElementMock_Attribute_Call struct {
	*mock.Call
}

// Attribute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ElementMock_Expecter) Attribute(ctx interface{}, name interface{}) *ElementMock_Attribute_Call {
	return &ElementMock_Attribute_Call{Call: _e.mock.On("Attribute", ctx, name)}
}

func (_c *ElementMock_Attribute_Call) Run(run func(ctx context.Context, name string)) *ElementMock_Attribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElementMock_Attribute_Call) Return(s *string, err error) *ElementMock_Attribute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ElementMock_Attribute_Call) RunAndReturn(run func(ctx context.Context, name string) (*string, error)) *ElementMock_Attribute_Call {
	_c.Call.Return(run)
	return _c
}

// Click provides a mock function for the type ElementMock
func (_mock *ElementMock) Click(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Click")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElementMock_Click_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Click'
type ElementMock_Click_Call struct {
	*mock.Call
}

// Click is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ElementMock_Expecter) Click(ctx interface{}) *ElementMock_Click_Call {
	return &ElementMock_Click_Call{Call: _e.mock.On("Click", ctx)}
}

func (_c *ElementMock_Click_Call) Run(run func(ctx context.Context)) *ElementMock_Click_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElementMock_Click_Call) Return(err error) *ElementMock_Click_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElementMock_Click_Call) RunAndReturn(run func(ctx context.Context) error) *ElementMock_Click_Call {
	_c.Call.Return(run)
	return _c
}

// Element provides a mock function for the type ElementMock
func (_mock *ElementMock) Element(ctx context.Context, selector string) (repository.Element, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Element")
	}

	var r0 repository.Element
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Element, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Element); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Element)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElementMock_Element_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Element'
type ElementMock_Element_Call struct {
	*mock.Call
}

// Element is a helper method to define mock.On call
//   - ctx context.Context
//   - selector string
func (_e *ElementMock_Expecter) Element(ctx interface{}, selector interface{}) *ElementMock_Element_Call {
	return &ElementMock_Element_Call{Call: _e.mock.On("Element", ctx, selector)}
}

func (_c *ElementMock_Element_Call) Run(run func(ctx context.Context, selector string)) *ElementMock_Element_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElementMock_Element_Call) Return(element repository.Element, err error) *ElementMock_Element_Call {
	_c.Call.Return(element, err)
	return _c
}

func (_c *ElementMock_Element_Call) RunAndReturn(run func(ctx context.Context, selector string) (repository.Element, error)) *ElementMock_Element_Call {
	_c.Call.Return(run)
	return _c
}

// ElementX provides a mock function for the type ElementMock
func (_mock *ElementMock) ElementX(ctx context.Context, selector string) (repository.Element, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for ElementX")
	}

	var r0 repository.Element
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.Element, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.Element); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Element)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElementMock_ElementX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElementX'
type ElementMock_ElementX_Call struct {
	*mock.Call
}

// ElementX is a helper method to define mock.On call
//   - ctx context.Context
//   - selector string
func (_e *ElementMock_Expecter) ElementX(ctx interface{}, selector interface{}) *ElementMock_ElementX_Call {
	return &ElementMock_ElementX_Call{Call: _e.mock.On("ElementX", ctx, selector)}
}

func (_c *ElementMock_ElementX_Call) Run(run func(ctx context.Context, selector string)) *ElementMock_ElementX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElementMock_ElementX_Call) Return(element repository.Element, err error) *ElementMock_ElementX_Call {
	_c.Call.Return(element, err)
	return _c
}

func (_c *ElementMock_ElementX_Call) RunAndReturn(run func(ctx context.Context, selector string) (repository.Element, error)) *ElementMock_ElementX_Call {
	_c.Call.Return(run)
	return _c
}

// Input provides a mock function for the type ElementMock
func (_mock *ElementMock) Input(ctx context.Context, text string) error {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Input")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElementMock_Input_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Input'
type ElementMock_Input_Call struct {
	*mock.Call
}

// Input is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *ElementMock_Expecter) Input(ctx interface{}, text interface{}) *ElementMock_Input_Call {
	return &ElementMock_Input_Call{Call: _e.mock.On("Input", ctx, text)}
}

func (_c *ElementMock_Input_Call) Run(run func(ctx context.Context, text string)) *ElementMock_Input_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElementMock_Input_Call) Return(err error) *ElementMock_Input_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElementMock_Input_Call) RunAndReturn(run func(ctx context.Context, text string) error) *ElementMock_Input_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function for the type ElementMock
func (_mock *ElementMock) Text(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Text")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElementMock_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type ElementMock_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ElementMock_Expecter) Text(ctx interface{}) *ElementMock_Text_Call {
	return &ElementMock_Text_Call{Call: _e.mock.On("Text", ctx)}
}

func (_c *ElementMock_Text_Call) Run(run func(ctx context.Context)) *ElementMock_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ElementMock_Text_Call) Return(s string, err error) *ElementMock_Text_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ElementMock_Text_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *ElementMock_Text_Call {
	_c.Call.Return(run)
	return _c
}
