// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/pkg/logger"
)

// NewLoggerMock creates a new instance of LoggerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerMock {
	mock := &LoggerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoggerMock is an autogenerated mock type for the Logger type
type LoggerMock struct {
	mock.Mock
}

type LoggerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerMock) EXPECT() *LoggerMock_Expecter {
	return &LoggerMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type LoggerMock
func (_mock *LoggerMock) Error(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// LoggerMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type LoggerMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *LoggerMock_Expecter) Error(msg interface{}, args ...interface{}) *LoggerMock_Error_Call {
	return &LoggerMock_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *LoggerMock_Error_Call) Run(run func(msg string, args ...any)) *LoggerMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LoggerMock_Error_Call) Return() *LoggerMock_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Error_Call) RunAndReturn(run func(msg string, args ...any)) *LoggerMock_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type LoggerMock
func (_mock *LoggerMock) Info(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// LoggerMock_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type LoggerMock_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *LoggerMock_Expecter) Info(msg interface{}, args ...interface{}) *LoggerMock_Info_Call {
	return &LoggerMock_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *LoggerMock_Info_Call) Run(run func(msg string, args ...any)) *LoggerMock_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LoggerMock_Info_Call) Return() *LoggerMock_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Info_Call) RunAndReturn(run func(msg string, args ...any)) *LoggerMock_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type LoggerMock
func (_mock *LoggerMock) Warn(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// LoggerMock_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type LoggerMock_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *LoggerMock_Expecter) Warn(msg interface{}, args ...interface{}) *LoggerMock_Warn_Call {
	return &LoggerMock_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, args...)...)}
}

func (_c *LoggerMock_Warn_Call) Run(run func(msg string, args ...any)) *LoggerMock_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LoggerMock_Warn_Call) Return() *LoggerMock_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Warn_Call) RunAndReturn(run func(msg string, args ...any)) *LoggerMock_Warn_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type LoggerMock
func (_mock *LoggerMock) With(args ...any) logger.Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(...any) logger.Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// LoggerMock_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type LoggerMock_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...any
func (_e *LoggerMock_Expecter) With(args ...interface{}) *LoggerMock_With_Call {
	return &LoggerMock_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *LoggerMock_With_Call) Run(run func(args ...any)) *LoggerMock_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *LoggerMock_With_Call) Return(logger1 logger.Logger) *LoggerMock_With_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *LoggerMock_With_Call) RunAndReturn(run func(args ...any) logger.Logger) *LoggerMock_With_Call {
	_c.Call.Return(run)
	return _c
}
