// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/internal/domain"
)

// NewOzonParserMock creates a new instance of OzonParserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOzonParserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OzonParserMock {
	mock := &OzonParserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OzonParserMock is an autogenerated mock type for the OzonParser type
type OzonParserMock struct {
	mock.Mock
}

type OzonParserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OzonParserMock) EXPECT() *OzonParserMock_Expecter {
	return &OzonParserMock_Expecter{mock: &_m.Mock}
}

// GetAllProducts provides a mock function for the type OzonParserMock
func (_mock *OzonParserMock) GetAllProducts(ctx context.Context, name string, priceFrom float64, priceTo float64) ([]domain.Product, error) {
	ret := _mock.Called(ctx, name, priceFrom, priceTo)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, float64) ([]domain.Product, error)); ok {
		return returnFunc(ctx, name, priceFrom, priceTo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, float64) []domain.Product); ok {
		r0 = returnFunc(ctx, name, priceFrom, priceTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, float64, float64) error); ok {
		r1 = returnFunc(ctx, name, priceFrom, priceTo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OzonParserMock_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type OzonParserMock_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - priceFrom float64
//   - priceTo float64
func (_e *OzonParserMock_Expecter) GetAllProducts(ctx interface{}, name interface{}, priceFrom interface{}, priceTo interface{}) *OzonParserMock_GetAllProducts_Call {
	return &OzonParserMock_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", ctx, name, priceFrom, priceTo)}
}

func (_c *OzonParserMock_GetAllProducts_Call) Run(run func(ctx context.Context, name string, priceFrom float64, priceTo float64)) *OzonParserMock_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OzonParserMock_GetAllProducts_Call) Return(products []domain.Product, err error) *OzonParserMock_GetAllProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *OzonParserMock_GetAllProducts_Call) RunAndReturn(run func(ctx context.Context, name string, priceFrom float64, priceTo float64) ([]domain.Product, error)) *OzonParserMock_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}
