// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/marketplace-parser-service/internal/domain"
)

// NewParserServiceMock creates a new instance of ParserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParserServiceMock {
	mock := &ParserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ParserServiceMock is an autogenerated mock type for the ParserService type
type ParserServiceMock struct {
	mock.Mock
}

type ParserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ParserServiceMock) EXPECT() *ParserServiceMock_Expecter {
	return &ParserServiceMock_Expecter{mock: &_m.Mock}
}

// GetProductsList provides a mock function for the type ParserServiceMock
func (_mock *ParserServiceMock) GetProductsList(ctx context.Context, name string, priceFrom float64, priceTo float64) ([]domain.Product, error) {
	ret := _mock.Called(ctx, name, priceFrom, priceTo)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsList")
	}

	var r0 []domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, float64) ([]domain.Product, error)); ok {
		return returnFunc(ctx, name, priceFrom, priceTo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, float64) []domain.Product); ok {
		r0 = returnFunc(ctx, name, priceFrom, priceTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, float64, float64) error); ok {
		r1 = returnFunc(ctx, name, priceFrom, priceTo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ParserServiceMock_GetProductsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsList'
type ParserServiceMock_GetProductsList_Call struct {
	*mock.Call
}

// GetProductsList is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - priceFrom float64
//   - priceTo float64
func (_e *ParserServiceMock_Expecter) GetProductsList(ctx interface{}, name interface{}, priceFrom interface{}, priceTo interface{}) *ParserServiceMock_GetProductsList_Call {
	return &ParserServiceMock_GetProductsList_Call{Call: _e.mock.On("GetProductsList", ctx, name, priceFrom, priceTo)}
}

func (_c *ParserServiceMock_GetProductsList_Call) Run(run func(ctx context.Context, name string, priceFrom float64, priceTo float64)) *ParserServiceMock_GetProductsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ParserServiceMock_GetProductsList_Call) Return(products []domain.Product, err error) *ParserServiceMock_GetProductsList_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ParserServiceMock_GetProductsList_Call) RunAndReturn(run func(ctx context.Context, name string, priceFrom float64, priceTo float64) ([]domain.Product, error)) *ParserServiceMock_GetProductsList_Call {
	_c.Call.Return(run)
	return _c
}
