// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIV1MarketplaceParserServiceProductsSearchGetParams is parameters of GET /api/v1/marketplace-parser-service/products/search operation.
type APIV1MarketplaceParserServiceProductsSearchGetParams struct {
	// Full or partial name of the product being searched for.
	Name string
	// Lower price limit in rubles.
	PriceFrom OptFloat64 `json:",omitempty,omitzero"`
	// Upper price limit in rubles.
	PriceTo OptFloat64 `json:",omitempty,omitzero"`
}

func unpackAPIV1MarketplaceParserServiceProductsSearchGetParams(packed middleware.Parameters) (params APIV1MarketplaceParserServiceProductsSearchGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "price_from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PriceFrom = v.(OptFloat64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "price_to",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PriceTo = v.(OptFloat64)
		}
	}
	return params
}

func decodeAPIV1MarketplaceParserServiceProductsSearchGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1MarketplaceParserServiceProductsSearchGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: price_from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "price_from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPriceFromVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotPriceFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PriceFrom.SetTo(paramsDotPriceFromVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.PriceFrom.Get(); ok {
					if err := func() error {
						if err := (validate.Float{}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "price_from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: price_to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "price_to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPriceToVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotPriceToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.PriceTo.SetTo(paramsDotPriceToVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.PriceTo.Get(); ok {
					if err := func() error {
						if err := (validate.Float{}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "price_to",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
