// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1MarketplaceParserServiceProductsSearchGet implements GET /api/v1/marketplace-parser-service/products/search operation.
//
// Search for products by name and price range.
//
// GET /api/v1/marketplace-parser-service/products/search
func (UnimplementedHandler) APIV1MarketplaceParserServiceProductsSearchGet(ctx context.Context, params APIV1MarketplaceParserServiceProductsSearchGetParams) (r APIV1MarketplaceParserServiceProductsSearchGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
